usuarios/Controllers/OvinoCaprinoController.cs
using Nest;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using usuarios;
using usuarios.Models;

namespace WebAgroEsi.Controllers
{
    public class OvinoCaprinoController : Controller
    {
        ElasticClient elasticClient = Broker.EsClient();
        [HttpGet]
        public ActionResult Index(Busqueda busqueda)
        {
            List<Precio> precios = new List<Precio>();
            List<double> numerosMax = new List<double>();
            List<double> numerosMin = new List<double>();
            List<Noticia> noticias = new List<Noticia>();
            List<string> fechasMax = new List<string>();
            List<string> fechasMin = new List<string>();
            string prod = null;
            string var = null;
            if (!string.IsNullOrEmpty(busqueda.botonbuscar))
            {
                prod = busqueda.prodyvar(busqueda.producto)[0];
                var = busqueda.prodyvar(busqueda.producto)[1];

                var filtro = elasticClient.Search<Precio>(s => s
                                                         .Index("agroesi")
                                                         .Type("precio")
                                                         .Size(12)
                                                         .Sort(ss => ss.Ascending(p => p.fecha))
                                                         .Query(q => q
                                                         .Bool(qb => qb
                                                         .Must(
                                                                bs => bs.Term(p => p.codigo, busqueda.producto.ToLower()),
                                                                bs => bs.Term(p => p.año, busqueda.campaña),
                                                                bs => bs.Term(p => p.nomMes, busqueda.mes)
                                                                ))));
                if (filtro.Hits.Count==0)
                {
                    return RedirectToAction("NoResult");
                }

                var estadisticas = elasticClient.Search<Precio>(s => s
                                                        .Index("agroesi")
                                                        .Type("precio")
                                                        .Size(10000)
                                                        .Sort(ss => ss.Descending(p => p.precio))
                                                        .Query(q => q.Term(p => p.codigo, busqueda.producto.ToLower())));

                var ultimo_precio = elasticClient.Search<Precio>(s => s
                                                        .Index("agroesi")
                                                        .Type("precio")
                                                        .Size(10000)
                                                        .Sort(ss => ss.Descending(p => p.fecha))
                                                        .Query(q => q.Term(p => p.codigo, busqueda.producto.ToLower())));

                var news = elasticClient.Search<Noticia>(n => n
                                                .Index("rss")
                                                .Type("noticia")
                                                .Size(5)
                                                .Sort(ss => ss.Descending(p => p.fecha))
                                                .Query(q => q
                                                .Bool(qb => qb
                                                .Must(
                                                    bs => bs.Term(ns => ns.codigo, "gn"),
                                                    bs => bs.Term(ns => ns.año, 2017)))));

                foreach (var hit in news.Hits)
                {
                    Noticia n = new Noticia();
                    n.titulo = hit.Source.titulo;
                    n.link = hit.Source.link;
                    n.descripcion = hit.Source.descripcion;
                    n.fecha = hit.Source.fecha;
                    noticias.Add(n);
                }
                busqueda.noticias = noticias;


                foreach (var hit in filtro.Hits)
                {

                    Precio p = new Precio();
                    p.producto = prod;
                    p.variedad = var;
                    p.precio = Convert.ToDouble(hit.Source.precio);
                    p.medida = hit.Source.medida;
                    p.fecha = hit.Source.fecha;
                    p.tipoPrecio = hit.Source.tipoPrecio;
                    precios.Add(p);
                    if (p.tipoPrecio == "max")
                    {
                        numerosMax.Add(p.precio);
                        fechasMax.Add(p.fecha);
                        
                    }else
                    {
                        numerosMin.Add(p.precio);
                        fechasMin.Add(p.fecha);
                    }

                }
                busqueda.preciosMax = numerosMax;
                busqueda.preciosMin = numerosMin;
                busqueda.resultados = precios;
                busqueda.maxHistorico = estadisticas.Hits.First().Source;
                busqueda.minHistorico = estadisticas.Hits.Last().Source;
                busqueda.actual = ultimo_precio.Hits.First().Source;
                busqueda.fechasMax = fechasMax;
                busqueda.fechasMin = fechasMin;

            }
            else
            {
                var estadisticas = elasticClient.Search<Precio>(s => s
                                                        .Index("agroesi")
                                                        .Type("precio")
                                                        .Size(10000)
                                                        .Sort(ss => ss.Descending(p => p.precio))
                                                        .Query(q => q.Term(p => p.codigo, "LC".ToLower())));

                var ultimo_precio = elasticClient.Search<Precio>(s => s
                                                        .Index("agroesi")
                                                        .Type("precio")
                                                        .Size(10000)
                                                        .Sort(ss => ss.Descending(p => p.fecha))
                                                        .Query(q => q.Term(p => p.codigo, "LC".ToLower())));

                var cargaIncial = elasticClient.Search<Precio>(s => s
                                                         .Index("agroesi")
                                                         .Type("precio")
                                                         .Size(12)
                                                         .Sort(ss => ss.Ascending(p => p.fecha))
                                                         .Query(q => q
                                                         .Bool(qb => qb
                                                         .Must(
                                                                bs => bs.Term(p => p.codigo, "LC".ToLower()),
                                                                bs => bs.Term(p => p.año, 2017),
                                                                bs => bs.Term(p => p.nomMes, "julio")
                                                                ))));

                var news = elasticClient.Search<Noticia>(n => n
                                                .Index("rss")
                                                .Type("noticia")
                                                .Size(5)
                                                .Sort(ss => ss.Descending(p => p.fecha))
                                                .Query(q => q
                                                .Bool(qb => qb
                                                .Must(
                                                    bs => bs.Term(ns => ns.codigo, "gn"),
                                                    bs => bs.Term(ns => ns.año, 2017)))));


                foreach (var hit in news.Hits)
                {
                    Noticia n = new Noticia();
                    n.titulo = hit.Source.titulo;
                    n.link = hit.Source.link;
                    n.descripcion = hit.Source.descripcion;
                    n.fecha = hit.Source.fecha;
                    noticias.Add(n);
                }
                busqueda.noticias = noticias;
                foreach (var hit in cargaIncial.Hits)
                {
                    Precio p = new Precio();
                    p.producto = "Leche";
                    p.variedad = "de cabra";
                    p.precio = Convert.ToDouble(hit.Source.precio);
                    p.medida = hit.Source.medida;
                    p.fecha = hit.Source.fecha;
                    p.tipoPrecio = hit.Source.tipoPrecio;
                    precios.Add(p);
                    if (p.tipoPrecio == "max")
                    {
                        numerosMax.Add(p.precio);
                        fechasMax.Add(p.fecha);

                    }
                    else
                    {
                        numerosMin.Add(p.precio);
                        fechasMin.Add(p.fecha);
                    }


                }
                busqueda.maxHistorico = estadisticas.Hits.First().Source;
                busqueda.minHistorico = estadisticas.Hits.Last().Source;
                busqueda.actual = ultimo_precio.Hits.First().Source;
                busqueda.preciosMax = numerosMax;
                busqueda.preciosMin = numerosMin;
                busqueda.resultados = precios;
                busqueda.fechasMax = fechasMax;
                busqueda.fechasMin = fechasMin;
            }

usuarios/Views/OvinoCaprino/Index.cshtml
@model usuarios.Models.Busqueda
@using Chart.Mvc.ComplexChart;
@using Chart.Mvc.Extensions;

@{
    ViewBag.Title = "Datos de precios";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="~/Scripts/Chart.js"></script>
<script src="~/Scripts/Chart.js"></script>

@using (Html.BeginForm("Index", "OvinoCaprino", FormMethod.Get))
{
    @Html.ValidationSummary(false)
    <div style="border-bottom:1px solid #bbb"><h1>Cuadro de mandos: </h1></div>
    <table style="border:0px; width:500px;">
        <tr>
            <td>
                <div class="editor-label" style="margin-left:5px">
                    @Html.LabelFor(model => model.producto)
                </div>

                <div class="list-inline" style="margin-left:5px">
                    @Html.DropDownListFor(model => model.producto, new SelectList(Model.productosOVCA, "Value", "Text"))
                </div>
            </td>
            <td>
                <div class="editor-label" style="margin-left:5px">
                    @Html.LabelFor(model => model.campaña)
                </div>

                <div class="list-inline" style="margin-left:10px">
                    @Html.DropDownListFor(model => model.campaña, new SelectList(Model.campañasAlbacete, "Value", "Text"))
                </div>
            </td>
            <td>
                <div class="editor-label" style="margin-left:15px">
                    @Html.LabelFor(model => model.mes)
                </div>

                <div class="list-inline" style="margin-left:10px">
                    @Html.DropDownListFor(model => model.mes, new SelectList(Model.mesesAño, "Value", "Text"))
                </div>
            </td>
            <td>
                <div class="editor-field" style="margin-left:10px; margin-top:24px">
                    <input name="botonbuscar" type="submit" value="Buscar" class="btn-primary" />
                </div>
            </td>
        </tr>
    </table>

    var barChart = new BarChart();
    barChart.ChartConfiguration.ScaleBeginAtZero = false;
    barChart.ChartConfiguration.ScaleGridLineColor = "rgba(0, 0, 0, 0.3)";
    barChart.ComplexData.Labels.AddRange(Model.fechasMin);
    barChart.ComplexData.Datasets.AddRange(new List<ComplexDataset>
                             {
                                new ComplexDataset
                                    {
                                        Data = Model.preciosMin,
                                        FillColor = "rgba(102, 51, 153,1)",
                                        StrokeColor = "rgba(220,220,220,1)",
                                        PointColor = "rgba(220,220,220,1)",
                                        PointStrokeColor = "#fff",
                                        PointHighlightFill = "#fff",
                                        PointHighlightStroke = "rgba(220,220,220,1)",
                                    }
                            });

    var lineChart = new LineChart();
    lineChart.ChartConfiguration.ScaleGridLineColor = "rgba(0, 0, 0, 0.3)";
    lineChart.ComplexData.Labels.AddRange(Model.fechasMax);
    lineChart.ComplexData.Datasets.AddRange(new List<ComplexDataset>
                             {
                                new ComplexDataset
                                    {
                                        Data = Model.preciosMin,
                                        FillColor = "rgba(255, 255, 255, 0)",
                                        StrokeColor = "rgba(0, 0, 0, 1)",
                                        PointColor = "rgba(240, 20, 159,1)",
                                        PointStrokeColor = "#fff",
                                        PointHighlightFill = "#fff",
                                        PointHighlightStroke = "rgba(220,220,220,1)",
                                    },
                                new ComplexDataset
                                    {
                                        Data = Model.preciosMax,
                                        FillColor = "rgba(255, 255, 255, 0)",
                                        StrokeColor = "rgba(0, 0, 0, 1)",
                                        PointColor = "rgba(20, 119, 240, 1)",
                                        PointStrokeColor = "#fff",
                                        PointHighlightFill = "#fff",
                                        PointHighlightStroke = "rgba(220,220,220,1)",
                                    }
                            });
    <div class="panel-body">
        <div class="col-md-3" title="Campañas: 1999-2017">
            <div class="well" style="background-color:white">
                <h2 class="text-center"><span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>19</h2>
                <h4 class="text-center">Número de campañas</h4>
            </div>
        </div>
        <div class="col-md-3" title="@Model.actual.fecha">
            <div class="well" style="background-color:white">
                <h2 class="text-center"><span class="glyphicon glyphicon-ok" aria-hidden="true"></span> @Model.actual.precio</h2>
                <h4 class="text-center">Valor más reciente</h4>
            </div>
        </div>
        <div class="col-md-3" title="@Model.maxHistorico.fecha">
            <div class="well" style="background-color:white">
                <h2 class="text-center"><span class="glyphicon glyphicon-hand-up" aria-hidden="true"></span> @System.Convert.ToDouble(Model.maxHistorico.precio)</h2>
                <h4 class="text-center">Máximo Histórico</h4>
            </div>
        </div>
        <div class="col-md-3" title="@Model.minHistorico.fecha">
            <div class="well" style="background-color:white">
                <h2 class="text-center"><span class="glyphicon glyphicon-hand-down" aria-hidden="true"></span>@System.Convert.ToDouble(Model.minHistorico.precio)</h2>
                <h4 class="text-center">Mínimo Histórico</h4>
            </div>
        </div>
        <div class="col-md-12">
            <div class="col-md-5" style="align-content:center">
                <h3>Comparativa de precios:</h3>
            </div>
            <div class="col-md-6" style="margin-top:30px">
                <div class="col-md-2" style="background-color:rgba(240, 20, 159,1); color:white"> <strong>Mínimo</strong> </div>
                <div class="col-md-1"></div>
                <div class="col-md-2" style="background-color:rgba(20, 119, 240, 1); color:white"> <strong>Máximo</strong> </div>
            </div>
        </div>
        <div class="col-md-8">
            <div class="col-md-5" style="margin-left:10px">
                <canvas width="320" height="350" id="left"></canvas>
                @Html.CreateChart("left", barChart)

            </div>
            <div class="col-md-5" style="margin-left:55px; margin-right:20px">
                <canvas width="320" height="350" id="right"></canvas>
                    @Html.CreateChart("right", lineChart)
               
            </div>
            @if (Model.resultados != null)
            {
                <table class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th>Producto</th>
                            <th>Variedad</th>
                            <th>Precio</th>
                            <th>Tipo precio</th>
                            <th>Medida</th>
                            <th>Fecha</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var product in Model.resultados)
                        {
                            <tr class="info">
                                <td align="center">@product.producto</td>
                                <td align="center">@product.variedad</td>
                                <td align="right">@product.precio</td>
                                <td align="center">@product.tipoPrecio</td>
                                <td align="center">@product.medida</td>
                                <td align="center">@product.fecha</td>
                            </tr>
                        }
                    </tbody>
                </table>

            }
        </div>
        <div class="col-md-4">
            <div class="list-group">
                @foreach (var noticia in Model.noticias)
                {
                    <a href="@noticia.link" target="_blank" class="list-group-item">
                        <h4 class="list-group-item-heading">@noticia.titulo</h4>
                    </a>

                }
            </div>
        </div>
    </div>

}

usuarios/Views/OvinoCaprino/NoResult.cshtml
@{
    ViewBag.Title = "NoResult";
}

<h2>No hay datos disponibles.</h2>