usuarios/Controllers/VacunoController.cs
using Nest;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using usuarios;
using usuarios.Models;

namespace WebAgroEsi.Controllers
{
    public class VacunoController : Controller
    {
        ElasticClient elasticClient = Broker.EsClient();
        [HttpGet]
 
        public ActionResult Index(Busqueda busqueda)
        {
            List<Precio> precios = new List<Precio>();
            List<double> numeros = new List<double>();
            List<Noticia> noticias = new List<Noticia>();
            List<string> fechas = new List<string>();
            string prod = null;
            string var = null;
            if (!string.IsNullOrEmpty(busqueda.botonbuscar))
            {
                prod = busqueda.prodyvar(busqueda.producto)[0];
                var = busqueda.prodyvar(busqueda.producto)[1];
                int año = System.Convert.ToInt16(busqueda.campaña);
                ISearchResponse<Precio> result = null;
                if (año>=2002 && año<=2016)
                {
                    result= elasticClient.Search<Precio>(s => s
                                                         .Index("agroesi")
                                                         .Type("precio")
                                                         .Size(12)
                                                         .Sort(ss => ss.Ascending(p => p.fecha))
                                                         .Query(q => q
                                                         .Bool(qb => qb
                                                         .Must(
                                                                bs => bs.Term(p => p.codigo, busqueda.producto.ToLower()),
                                                                bs => bs.Term(p => p.año, año)
                                                                ))));
                }
                else
                {
                    result = elasticClient.Search<Precio>(s => s
                                      .Index("agroesi")
                                      .Type("precio")
                                      .Size(12)
                                      .Sort(ss => ss.Ascending(p => p.fecha))
                                      .Query(q => q
                                      .Bool(qb => qb
                                      .Must(
                                             bs => bs.Term(p => p.codigo, busqueda.producto.ToLower()),
                                             bs => bs.Term(p => p.año, busqueda.campaña),
                                             bs => bs.Term(p => p.nomMes, busqueda.mes)
                                             ))));

                }

                if (result.Hits.Count == 0)
                {
                    return RedirectToAction("NoResult");
                }


                var estadisticas = elasticClient.Search<Precio>(s => s
                                                        .Index("agroesi")
                                                        .Type("precio")
                                                        .Size(10000)
                                                        .Sort(ss => ss.Descending(p => p.precio))
                                                        .Query(q => q
                                                        .Bool(qb => qb
                                                        .Must(
                                                                bs => bs.Term(p => p.codigo, busqueda.producto.ToLower()),
                                                                bs => bs.Range(c => c.Field(p => p.precio).GreaterThan(0).Relation(RangeRelation.Within))
                                                         ))));

                var ultimo_precio = elasticClient.Search<Precio>(s => s
                                                        .Index("agroesi")
                                                        .Type("precio")
                                                        .Size(10000)
                                                        .Sort(ss => ss.Descending(p => p.fecha))
                                                        .Query(q => q
                                                        .Bool(qb => qb
                                                        .Must(
                                                                bs => bs.Term(p => p.codigo, busqueda.producto.ToLower()),
                                                                bs => bs.Range(c => c.Field(p => p.precio).GreaterThan(0).Relation(RangeRelation.Within))
                                                         ))));

                foreach (var hit in result.Hits)
                {

                    Precio p = new Precio();
                    p.producto = prod;
                    p.variedad = var;
                    p.precio = Convert.ToDouble(hit.Source.precio);
                    p.medida = hit.Source.medida;
                    p.fecha = hit.Source.fecha;
                    p.tipoPrecio = hit.Source.tipoPrecio;
                    precios.Add(p);
                    numeros.Add(p.precio);
                    fechas.Add(p.fecha);



                }
                busqueda.precios = numeros;
                busqueda.resultados = precios;
                busqueda.maxHistorico = estadisticas.Hits.First().Source;
                busqueda.minHistorico = estadisticas.Hits.Last().Source;
                busqueda.actual = ultimo_precio.Hits.First().Source;
                busqueda.fechas = fechas;

            }
            else
            {
                var estadisticas = elasticClient.Search<Precio>(s => s
                                                        .Index("agroesi")
                                                        .Type("precio")
                                                        .Size(10000)
                                                        .Sort(ss => ss.Descending(p => p.precio))
                                                        .Query(q => q
                                                        .Bool(qb => qb
                                                        .Must(
                                                                bs => bs.Term(p => p.codigo, "TO200C1".ToLower()),
                                                                bs => bs.Range(c => c.Field(p => p.precio).GreaterThan(0).Relation(RangeRelation.Within))
                                                         ))));

                var ultimo_precio = elasticClient.Search<Precio>(s => s
                                                        .Index("agroesi")
                                                        .Type("precio")
                                                        .Size(10000)
                                                        .Sort(ss => ss.Descending(p => p.fecha))
                                                        .Query(q => q
                                                        .Bool(qb => qb
                                                        .Must(
                                                                bs => bs.Term(p => p.codigo, "TO200C1".ToLower()),
                                                                bs => bs.Range(c => c.Field(p => p.precio).GreaterThan(0).Relation(RangeRelation.Within))
                                                         ))));

                var cargaIncial = elasticClient.Search<Precio>(s => s
                                                         .Index("agroesi")
                                                         .Type("precio")
                                                         .Size(12)
                                                         .Sort(ss => ss.Ascending(p => p.fecha))
                                                         .Query(q => q
                                                         .Bool(qb => qb
                                                         .Must(
                                                                bs => bs.Term(p => p.codigo, "TO200C1".ToLower()),
                                                                bs => bs.Term(p => p.año, 2017),
                                                                bs => bs.Term(p => p.nomMes, "agosto"),
                                                                bs => bs.Range(c => c.Field(p => p.precio).GreaterThan(0).Relation(RangeRelation.Within))
                                                                ))));

                foreach (var hit in cargaIncial.Hits)
                {
                    Precio p = new Precio();
                    p.producto = "Ternero cruzado";
                    p.variedad = "1ª Calidad (Base 200kg)";
                    p.precio = Convert.ToDouble(hit.Source.precio);
                    p.medida = hit.Source.medida;
                    p.fecha = hit.Source.fecha;
                    p.tipoPrecio = hit.Source.tipoPrecio;
                    precios.Add(p);
                    numeros.Add(p.precio);
                    fechas.Add(p.fecha);


                }
                busqueda.maxHistorico = estadisticas.Hits.First().Source;
                busqueda.minHistorico = estadisticas.Hits.Last().Source;
                busqueda.actual = ultimo_precio.Hits.First().Source;
                busqueda.precios = numeros;
                busqueda.resultados = precios;
                busqueda.fechas = fechas;
            }




            return View(busqueda);
        }
        public ActionResult NoResult()
        {
            return View();
        }
    }
}

usuarios/Views/Vacuno/Index.cshtml
@model usuarios.Models.Busqueda
@using Chart.Mvc.ComplexChart;
@using Chart.Mvc.Extensions;

@{
    ViewBag.Title = "Datos de precios";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="~/Scripts/Chart.js"></script>
<script src="~/Scripts/Chart.js"></script>

@using (Html.BeginForm("Index", "Vacuno", FormMethod.Get))
{
    @Html.ValidationSummary(false)
    <div style="border-bottom:1px solid #bbb"><h1>Cuadro de mandos: </h1></div>
    <table style="border:0px; width:500px;">
        <tr>
            <td>
                <div class="editor-label" style="margin-left:5px">
                    @Html.LabelFor(model => model.producto)
                </div>

                <div class="list-inline" style="margin-left:5px">
                    @Html.DropDownListFor(model => model.producto, new SelectList(Model.productosVC, "Value", "Text"))
                </div>
            </td>
            <td>
                <div class="editor-label" style="margin-left:5px">
                    @Html.LabelFor(model => model.campaña)
                </div>

                <div class="list-inline" style="margin-left:5px">
                    @Html.DropDownListFor(model => model.campaña, new SelectList(Model.campañasTalavera, "Value", "Text"))
                </div>
            </td>
            <td>
                <div class="editor-label" style="margin-left:15px">
                    @Html.LabelFor(model => model.mes)
                </div>

                <div class="list-inline" style="margin-left:5px">
                    @Html.DropDownListFor(model => model.mes, new SelectList(Model.mesesAño, "Value", "Text"))
                </div>
            </td>
            <td>
                <div class="editor-field" style="margin-left:10px; margin-top:24px">
                    <input name="botonbuscar" type="submit" value="Buscar" class="btn-primary" />
                </div>
            </td>
        </tr>
    </table>

    var barChart = new BarChart();
    barChart.ChartConfiguration.ScaleBeginAtZero = false;
    barChart.ChartConfiguration.ScaleGridLineColor = "rgba(0, 0, 0, 0.3)";
    barChart.ComplexData.Labels.AddRange(Model.fechas);
    barChart.ComplexData.Datasets.AddRange(new List<ComplexDataset>
                             {
                                new ComplexDataset
                                    {
                                        Data = Model.precios,
                                        FillColor = "rgba(102, 51, 153,1)",
                                        StrokeColor = "rgba(220,220,220,1)",
                                        PointColor = "rgba(220,220,220,1)",
                                        PointStrokeColor = "#fff",
                                        PointHighlightFill = "#fff",
                                        PointHighlightStroke = "rgba(220,220,220,1)",
                                    }
                            });

    var lineChart = new LineChart();
    lineChart.ChartConfiguration.ScaleGridLineColor = "rgba(0, 0, 0, 0.3)";
    lineChart.ComplexData.Labels.AddRange(Model.fechas);
    lineChart.ComplexData.Datasets.AddRange(new List<ComplexDataset>
                             {
                                new ComplexDataset
                                    {
                                        Data = Model.precios,
                                        FillColor = "rgba(255, 255, 255, 0)",
                                        StrokeColor = "rgba(0, 0, 0, 1)",
                                        PointColor = "rgba(240, 20, 159,1)",
                                        PointStrokeColor = "#fff",
                                        PointHighlightFill = "#fff",
                                        PointHighlightStroke = "rgba(220,220,220,1)",
                                    }
                            });
    <div class="panel-body">
        <div class="col-md-3" title="2002-2017">
            <div class="well" style="background-color:white">
                <h2 class="text-center"><span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>16</h2>
                <h4 class="text-center">Número de campañas</h4>
            </div>
        </div>
        <div class="col-md-3" title="@Model.actual.fecha">
            <div class="well" style="background-color:white">
                <h2 class="text-center"><span class="glyphicon glyphicon-ok" aria-hidden="true"></span> @Model.actual.precio</h2>
                <h4 class="text-center">Valor más reciente</h4>
            </div>
        </div>
        <div class="col-md-3" title="@Model.maxHistorico.fecha">
            <div class="well" style="background-color:white">
                <h2 class="text-center"><span class="glyphicon glyphicon-hand-up" aria-hidden="true"></span> @System.Convert.ToDouble(Model.maxHistorico.precio)</h2>
                <h4 class="text-center">Máximo Histórico</h4>
            </div>
        </div>
        <div class="col-md-3" title="@Model.minHistorico.fecha">
            <div class="well" style="background-color:white">
                <h2 class="text-center"><span class="glyphicon glyphicon-hand-down" aria-hidden="true"></span>@System.Convert.ToDouble(Model.minHistorico.precio)</h2>
                <h4 class="text-center">Mínimo Histórico</h4>
            </div>
        </div>
        <div class="col-md-8">
            <div class="col-md-5" style="align-content:center">
                <h3>Evolución de precios:</h3>
            </div>
        </div>
        <div class="col-md-8">
            <div class="col-md-5" style="margin-right:40px">
                <canvas width="320" height="350" id="left"></canvas>
                @if (Model.precios.Count>2)
                {
                    @Html.CreateChart("left", barChart)
                }
                
            </div>
            <div class="col-md-5" style="margin-left:55px">
                <canvas width="320" height="350" id="center"></canvas>
                @if (Model.precios.Count > 2)
                {
                    @Html.CreateChart("center", lineChart)
                }
            </div>
            @if (Model.resultados != null)
            {
                <table class="table table-striped table-hover" style="margin-top:20px">
                    <thead>
                        <tr>
                            <th>Producto</th>
                            <th>Variedad</th>
                            <th>Precio</th>
                            <th>Tipo precio</th>
                            <th>Medida</th>
                            <th>Fecha</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var product in Model.resultados)
                        {
                            <tr class="info">
                                <td align="center">@product.producto</td>
                                <td align="center">@product.variedad</td>
                                <td align="right">@product.precio</td>
                                <td align="center">@product.tipoPrecio</td>
                                <td align="center">@product.medida</td>
                                <td align="center">@product.fecha</td>
                            </tr>
                        }
                    </tbody>
                </table>

            }
        </div>
    </div>

}

usuarios/Views/Vacuno/NoResult.cshtml
@{
    ViewBag.Title = "NoResult";
}

<h2>No hay datos disponibles.</h2>