usuarios/Controllers/NoticiaAGController.cs
using Nest;
using System.Collections.Generic;
using System.Web.Mvc;
using usuarios.Models;
using PagedList;

namespace usuarios.Controllers
{
    public class NoticiaAGController : Controller
    {
        ElasticClient elasticClient = Broker.EsClient();
        // GET: Noticia
        public ActionResult Index(int? page, Busqueda busqueda)
        {
            List<Noticia> noticias = new List<Noticia>();
            if (busqueda.campaña == null || busqueda.mes == null)
            {
                var news = elasticClient.Search<Noticia>(n => n
                                                                .Index("rss")
                                                                .Type("noticia")
                                                                .Size(60)
                                                                .Sort(s => s.Descending(sn => sn.fecha))
                                                                .Query(q => q
                                                                .Bool(qb => qb
                                                                .Must(
                                                                    bs => bs.Term(p => p.codigo, "ag"),
                                                                    bs => bs.Term(p => p.año, 2017)
                                                                ))));
                foreach (var hit in news.Hits)
                {
                    Noticia n = new Noticia();
                    n.etiquetas = hit.Source.etiquetas;
                    n.titulo = hit.Source.titulo;
                    n.descripcion = hit.Source.descripcion;
                    n.link = hit.Source.link;
                    n.imagen = hit.Source.imagen;
                    n.fecha = hit.Source.fecha;
                    n.año = hit.Source.año;
                    n.numMes = hit.Source.numMes;
                    noticias.Add(n);
                }

            }
            if (busqueda.campaña != null && busqueda.mes != null)
            {
                var news = elasticClient.Search<Noticia>(n => n
                                                                .Index("rss")
                                                                .Type("noticia")
                                                                .Size(12)
                                                                .Sort(s => s.Ascending(sn => sn.fecha))
                                                                .Query(q => q
                                                                .Bool(qb => qb
                                                                .Must(
                                                                    bs => bs.Term(p => p.codigo, "ag"),
                                                                    bs => bs.Term(p => p.año, busqueda.campaña),
                                                                    bs => bs.Term(p => p.nomMes, busqueda.mes)
                                                                ))));
                foreach (var hit in news.Hits)
                {
                    Noticia n = new Noticia();
                    n.etiquetas = hit.Source.etiquetas;
                    n.titulo = hit.Source.titulo;
                    n.descripcion = hit.Source.descripcion;
                    n.link = hit.Source.link;
                    n.imagen = hit.Source.imagen;
                    n.fecha = hit.Source.fecha;
                    n.año = hit.Source.año;
                    n.numMes = hit.Source.numMes;
                    noticias.Add(n);
                }


            }


            if (noticias.Count == 0)
            {
                return RedirectToAction("NoResult");
            }

            int pageSize = 12;
            int pageNumber = (page ?? 1);
            IPagedList<Noticia> listn = noticias.ToPagedList(pageNumber, pageSize);
            busqueda.listn = listn;
            return View(busqueda);
        }

        public ActionResult Buscar(string etiqueta)
        {
            List<Noticia> noticias = new List<Noticia>();
            string aux = null;
            if (etiqueta.Contains("-"))
            {
                aux = etiqueta.Split('-')[0];

            }
            if (etiqueta.Contains(" "))
            {

                aux = etiqueta.Split(' ')[0];
            }
            else
            {
                aux = etiqueta;
            }
            var news = elasticClient.Search<Noticia>(n => n
                                                                .Index("rss")
                                                                .Type("noticia")
                                                                .Size(12)
                                                                .Sort(s => s.Descending(sn => sn.fecha))
                                                                .Query(q => q
                                                                .Bool(qb => qb
                                                                .Must(
                                                                    bs => bs.Term(p => p.etiquetas, aux.ToLower()),
                                                                    bs => bs.Term(p => p.codigo, "AG".ToLower())


                                                                ))));
            if (news.Hits.Count == 0)
            {
                return RedirectToAction("NoResult");
            }

            foreach (var hit in news.Hits)
            {
                Noticia n = new Noticia();
                n.etiquetas = hit.Source.etiquetas;
                n.titulo = hit.Source.titulo;
                n.descripcion = hit.Source.descripcion;
                n.link = hit.Source.link;
                n.imagen = hit.Source.imagen;
                n.fecha = hit.Source.fecha;
                n.año = hit.Source.año;
                n.numMes = hit.Source.numMes;
                noticias.Add(n);
            }
            return View(noticias);
        }
        public ActionResult BuscarF(int mes, int año)
        {
            List<Noticia> noticias = new List<Noticia>();
            var news = elasticClient.Search<Noticia>(n => n
                                                                .Index("rss")
                                                                .Type("noticia")
                                                                .Size(36)
                                                                .Sort(s => s.Ascending(sn => sn.fecha))
                                                                .Query(q => q
                                                                .Bool(qb => qb
                                                                .Must(
                                                                    bs => bs.Term(p => p.codigo, "AG".ToLower()),
                                                                     bs => bs.Term(p => p.año, año),
                                                                      bs => bs.Term(p => p.numMes, mes)


                                                                ))));
            if (news.Hits.Count == 0)
            {
                return RedirectToAction("NoResult");
            }

            foreach (var hit in news.Hits)
            {
                Noticia n = new Noticia();
                n.etiquetas = hit.Source.etiquetas;
                n.titulo = hit.Source.titulo;
                n.descripcion = hit.Source.descripcion;
                n.link = hit.Source.link;
                n.imagen = hit.Source.imagen;
                n.fecha = hit.Source.fecha;
                n.año = hit.Source.año;
                n.numMes = hit.Source.numMes;
                noticias.Add(n);
            }
            return View(noticias);
        }
        public ActionResult NoResult()
        {
            return View();
        }
    }
}

usuarios/Views/NoticiaAG/Buscar.cshtml
@model List<usuarios.Models.Noticia>
@{
    ViewBag.Title = "Buscador";
}

<h2>Resultados de la busqueda: </h2>

<div class="panel-body">
   
        <div class="col-md-12" style="margin-top:15px;">
           @foreach (var noti in Model)
           {
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h3 class="panel-title"><a href="@noti.link" target="_blank">@noti.titulo</a></h3>
                    </div>
                    <div class="panel-body">
                        <img src="@noti.imagen" style="width:300px;" />
                        <p></p>
                        @{
                            var etiquetas1 = noti.etiquetas.Split(',');
                            foreach (var etiqueta in etiquetas1)
                            {
                                if (etiqueta != "")
                                {
                                    <a href="@Url.Action("Buscar", "NoticiaAG", new { etiqueta=etiqueta})"><span class="label label-info">@etiqueta</span></a>
                                }
                            }
                        }
                        <p></p>
                        <a href="@Url.Action("BuscarF","NoticiaAG", new { mes = noti.numMes, año =noti.año})"><span class="label label-success">@noti.fecha</span></a>
                    </div>
                </div>

            }
        </div>    
</div>

usuarios/Views/NoticiaAG/BuscarF.cshtml
@model List<usuarios.Models.Noticia>
@{
    ViewBag.Title = "Buscador";
}

<h2>Resultados de la busqueda: </h2>

<div class="panel-body">
   
        <div class="col-md-12" style="margin-top:15px;">
           @foreach (var noti in Model)
           {
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <h3 class="panel-title"><a href="@noti.link" target="_blank">@noti.titulo</a></h3>
                        </div>
                        <div class="panel-body">
                            @if (noti.imagen != "")
                            {
                                <img src="@noti.imagen" style="width:300px;" />
                            }
                            <p></p>
                            @{
                                var etiquetas1 = noti.etiquetas.Split(',');
                                foreach (var etiqueta in etiquetas1)
                                {
                                    if (etiqueta != "")
                                    {
                                        <a href="@Url.Action("Buscar", "NoticiaAG", new { etiqueta=etiqueta})"><span class="label label-info">@etiqueta</span></a>
                                    }
                                }
                            }
                            <p></p>
                            <span class="label label-success">@noti.fecha</span>
                        </div>
                    </div>
        
            }
        </div>    
</div>

usuarios/Views/NoticiaAG/Index.cshtml
@model usuarios.Models.Busqueda
@using PagedList.Mvc;
@{
    ViewBag.Title = "Noticias Agricultura";
}
<div style="border-bottom:1px solid #bbb"><h1>Mis noticias: </h1></div>
@using (Html.BeginForm("Index", "NoticiaAG", FormMethod.Get))
{
    <table style="border:0px; width:380px;">
        <tr>
            <td>
                <div class="editor-label" style="margin-left:5px; margin-top:20px">
                    @Html.LabelFor(model => model.campaña)
                    @Html.DropDownListFor(model => model.campaña, new SelectList(Model.campañasAG, "Value", "Text"))
                </div>
            </td>
            <td>
                <div class="editor-label" style="margin-top:17px">
                    @Html.LabelFor(model => model.mes)
                    @Html.DropDownListFor(model => model.mes, new SelectList(Model.mesesAño, "Value", "Text"))
                    <input name="botonbuscar" type="submit" value="Buscar" class="btn-primary" style="margin-left:10px" />
                </div>
            </td>
        </tr>
    </table>
}

@{
    var noticias = Model.listn.ToList();
}

<div class="panel-body">

    <div class="col-md-12" style="margin-top:15px;">
        @foreach (var noti in noticias)
        {
            <div class="col-md-4">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h3 class="panel-title"><a href="@noti.link" target="_blank">@noti.titulo</a></h3>
                    </div>
                    <div class="panel-body">
                        <img src="@noti.imagen" style="width:300px; height:300px" />
                        <p></p>
                        @{
                            var etiquetas1 = noti.etiquetas.Split(',');
                            foreach (var etiqueta in etiquetas1)
                            {
                                if (etiqueta != "")
                                {
                                    <a href="@Url.Action("Buscar", "NoticiaAG", new { etiqueta=etiqueta})"><span class="label label-info">@etiqueta</span></a>
                                }
                            }
                        }
                        <p></p>
                        <a href="@Url.Action("BuscarF","NoticiaAG", new { mes = noti.numMes, año =noti.año})"><span class="label label-success">@noti.fecha</span></a>
                    </div>
                </div>
            </div>
                            }
    </div>
</div>

Pagina @(Model.listn.PageCount < Model.listn.PageNumber ? 0 : Model.listn.PageNumber) de @Model.listn.PageCount
@Html.PagedListPager(Model.listn, page => Url.Action("Index", new { page, Model }))

usuarios/Views/NoticiaAG/NoResult.cshtml
@{
    ViewBag.Title = "NoResult";
}

<h2>No hay datos disponibles.</h2>